### PR TITLE
Add new term "euflammation"

### PR DESCRIPTION
**Pull request by trushaadeshara8**
CONSO00361 	Trusha  	Euflammation	biological process 	pmid:24929192	A peripheral inflammation that does not cause overt sickness behavior, yet primes the immune system to provide more resistance to a subsequent inflammatory stimulation as “euflammation.”

### CODE REVIEW

**Comment by trushaadeshara8** [comment]
@cthoyt could not fix the error

**Comment by cthoyt** [comment]
Please send me your ORCID identifier (https://orcid.org) and I'll add it to the curators file so it can validate properly

**Comment by trushaadeshara8** [comment]
@cthoyt my ORCID identifier: https://orcid.org/0000-0002-8929-4724

**Comment by cthoyt** [comment]
Could you please find two or three more references mentioning this term? Or some synonyms?

**Comment by trushaadeshara8** [comment]
> 
> 
> Could you please find two or three more references mentioning this term? Or some synonyms?

Euflammation attenuates peripheral inflammation-induced neuroinflammation and mitigates immune-to-brain signaling, by Liu X et al. PMID:26812118.

There are not lot of papers on this topic.

**Comment by cthoyt** [comment]
Okay, please put that inside the file... And keep looking for a few more. I have the feeling that this is called something else by other scientists

**Comment by cthoyt** [comment]
@trushaadeshara8 @sgebel Update???

**Comment by cthoyt** [comment]
More references at https://lmgtfy.com/?q=euflammation

**Pull request closed without merging**
